spring.application.name=DENTVISION_BACKEND_SPRINGBOOT
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://database-1.clg6gcmkex9d.us-east-2.rds.amazonaws.com:3306/db_dentivision
spring.datasource.username=root
spring.datasource.password=Slgy74jVwEJ0U3v2EeQt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=mySecretKey
jwt.expiration=86400000

# Logging
logging.level.com.sena.creyese.dentvision_backend_springboot=DEBUG
